package com.androiddevs.mvvmnewsapp.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

// this annotation tells android studio that this is will be a table in our database
// with author, content, description, etc. columns and each row will be an entry
@Entity(
    tableName = "articles"
)
data class Article(
    @PrimaryKey(autoGenerate = true) // this line and next are added manually, the rest are created by JSON to data class plugin
    var id: Int? = null, // not all articles will be saved, so not all need ID's, for saved once ID will be autoGenerated

    val author: String,
    val content: String,
    val description: String,
    val publishedAt: String,
    val source: Source,
    val title: String,
    val url: String,
    val urlToImage: String

    //step 9.1
) : Serializable {

    // step 9+ to fix NullPointerException error
    override fun hashCode(): Int {
        var result = id.hashCode()
        if(url.isEmpty()){
            result = 31 * result + url.hashCode()
        }
        return result
    }
}
